image: gitpod/workspace-full

tasks:
  - name: Verification about Node and PNPM version & install dependencies
    init: |
      node -v 
      pnpm -v
      pnpm install
      gp sync-done pnpm-global-install
  
  - name: Packages directory
    init: gp sync-await pnpm-global-install
    command: |
      cd packages
      echo ""

  - name: Test directory
    init: gp sync-await pnpm-global-install
    command: |
      cd test
      pnpm install
      pnpm run test

  - name: Website directory
    init: gp sync-await pnpm-global-install
    command: |
      cd website
      pnpm install
      pnpm run dev

ports:
  - name: Website
    port: 3000
    visibility: public
    onOpen: open-browser