image: gitpod/workspace-full

tasks:
  - name: Verification about Node and PNPM version & install dependencies
    init: |
      node -v 
      pnpm -v
      pnpm install
  
  - name: Run Packages directory
    command: |
      cd packages
      echo ""

  - name: Run test directory
    command: |
      cd test
      pnpm install
      pnpm run test

  - name: Run Website directory
    command: |
      pnpm install
      pnpm run dev

ports:
  - name: Website
    port: 3000
    visibility: public
    onOpen: open-browser